#install.packages('data.table')
library(data.table)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv", destfile = "getdata_data_ss06hid.csv",method = "curl")
data = read.csv("getdata_data_ss06hid.csv")
table = as.data.table(data)
table = read.table("getdata_data_ss06hid.csv")
table = fread("getdata_data_ss06hid.csv")
sum(table$VAL == 24 & !is.na(table$VAL))

#install.packages("xlsx")
library(xlsx)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx", "getdata_data_DATA.gov_NGAP.xlsx",method = "curl")
dat=read.xlsx(colIndex = 7:15, startRow = 18,endRow = 23, sheetIndex = 1,"getdata_data_DATA.gov_NGAP.xlsx" )
sum(dat$Zip*dat$Ext,na.rm=T) 

#install.packages("XML")
library(XML)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml", "getdata_data_restaurants.xml",method = "curl")
xml = xmlTreeParse("getdata_data_restaurants.xml",useInternalNodes = TRUE)
rootnode = xmlRoot(xml)
sum(xpathSApply(rootnode, "//zipcode",xmlValue) == 21231)